---
title: The dark side of the force is the worst
author: ""
date: ""
output:
  word_document:
    reference_docx: manuscriptstyle.docx
csl: plant-cell-environment.csl
bibliography: references.bib
---

\
Rey NoLastNameYet^1^, Han Solo^1^, Obi-Wan Kenobi^1^, Leia Organa^2^, Luke Skywalker^3^.

\
^1^ Department of Biology, Colgate University, Hamilton, NY, USA 13446
\
^2^ Centre of Excellence for a Peacful Universer, Planet Alderaan
\
^2^ Jedi Extraordinaire, Planet Tatooine

\
Author for Correspondence:
\
*Rey NoLastNameYet*
\
*Tel: +61 1 1234 1234*
\
*Email:LastJedi@gmail.com*
\
\
\
\

**Running Title**
\
Come to the light side


#Introduction

The YAML for a proper manuscript is more complicated than the basic markdown. These new options allow you to output a standard looking word document, set the formatting rules for you word document, access citations to cite properly and generate a bibliography and make sure your bibliography is generated in the style of your choosen mansucript.  In the methods sections I will step through how each of these work.  Importantly, you now have all the bits and pieces, so just adapt this template to your first manuscript.

\

Remember the goal.  With R, we can summarize, analyze and visualize our data. Then R markdown conveintly allows us to insert our work (as code) around a text! This means you no longer have to use excel, sigmaplot, SPSS/SAS and Endnote independently to make a manuscript.  If this doesnt convince you to code, then I dont know what will.

## Text tricks

Typing in markdown becomes second nature when you dont have to repeatedly use your mouse to highlight and format individual characters in your text.  Here, are some of the basics again:

\

Wrap text with ~ and ^ for ~subscript~ or a ^superscipt^. Wrapping text in one or two \*asterisks\ allows you to **bold** or *italicise* text.  There will be some rare instances where you want characters that also hold special meaning in markdown (i.e. asterisks). You can backslash around the characters to print the literal symbol (hardly ever need to do this).

\

Look the the code for the first page of the manuscript. You can easily add line breaks with backslashes to make your document look like you want. If you manually add space (or not) above and below the backslashes your document will render differently.  Just play around with them.

\

Equations and special symbols are not so bad either.  Just like in any word processor, the crazier the equation to the more difficult they are to make. Markdown using Latex to generate them, so they format may be familiar to some.  Wrap your equations in double dollar signs.  Markdown nicely previews what it will look like. Here are some examples:

\
Equation (1)
$$K_L = \frac{E_L}{\Psi_{pd}~-\Psi_L}$$

\

Because markdown is using Latex, subscripts and superscripts are a little different.  I have provided examples of both with the fraction above.  This should cover nearly all your basic equation needs. In mathm mode, ^ means supercript and _ means subscript.  If you can multiple characters that need either, wrap them in {}.

\
Equation (2)
$$\Delta_o = \alpha^i - \Gamma{gm} - \Delta^ef - \tau^{abc}$$

\

Here is one last ridiulous equation:

\
Equation (3)
$$
\begin{aligned}
g_m = \left(\frac{1+t}{1-t}\left(b-a_i-\frac{eR_d}{A+R_d}\right)\frac{A}{C_a}\right) / \left(\Delta_i-\Delta_o-\Delta_e-\Delta_f\right)
\end{aligned}
$$

Greek symbols are easily inserted using math mode, both in equations (see above) and in text  For text, just wrap them in single dollar signs.  Note the use of the backslash, which tells markdown to use the symbols. Rememeber that there can be different symbols for upper or lower case greek letters. Here are some examples of putting text tricks together to represent abbreviations or units in your manscript. Leaves used for gas exchange were immediately sampled for midday water potential ($\Psi_L$). Leaf water potentials and transpiration (*E*~L~, mmol m^-2^ s^-1^) from gas exchange in the leaf cuvette were then used to calculate leaf-specific hydraulic conductance (*K*~L~, mmol m^-2^ s^-1^ MPa^-1^).*A*~max~ measurements were made at a PPFD of 1800 $\mu$mol m^-1^ s^-1^ and [CO~2~] of 1800 $\mu$l l^-1^, with leaf temperature held constant at 25 &deg;C.  

\

There are some special symbols you may have to look up. The &deg; and &permil; symbols are some of them (but now you have it!). Since markdown has so many outputs (pdf, html and word) it accepts all kind of html, css, unicode or latex input for special symbols.  All of them are easily found on Google.  Here is the degree symbol using hex and html codes I found online (make sure and remember the & and ;): 15 &#xb0; 17 &#176; 21 &deg;. Look at https://www.w3schools.com/html/html_symbols.asp for some more examples. The HTML Entity codes are the best (&uarr; , &larr;, &reg;), as they will be easy to recognize and re-use.

\

That is basically it for text tricks.  Once you start learning to type in markdown (which takes very little time), you will loath having to type while using a mouse to highlight and change things.  Some of you are likely using google docs, which means you may be learning key board shortcuts.  This will feel right at home for you.  


# Methods

## manuscriptstyle.docx

Look back up in the YAML.  In addition to setting 'word' as an output we have an additioanl agrument: **reference_docx: manuscriptstyle.docx**.  This command is telling markdown to use the *manuscriptstyle.docx* file as a source to format our rendered word document.  Notice how we no longer render the ugly word document with blue font.  No look in the folder for this markdown file and find the file.  Click on it and open it up. This file is just a simple word file with a few sections.  Markdown *steals* the formatting in this document and applies it to yours.

\

Think about what this really means and how awesome it is.  Let's say that your paper gets rejected (boo) and the new journal you are submitting too requires different formats (page numbers, spacing, fonts, etc.). All you need to do is make quick changes in your *manuscriptstyle.docx* and press save. Voila!

\

Importantly, when updating *manuscriptstyle.docx* you must actually change the formatting style of the document, meaning highlighting text and changing style will not necessarily work.  Make sure you are changing the global style of the document.  You have control over everything here, such as simple things like line spacing to more detailed formatting of paragrpahs and headings.  All will be *stolen* by markdown.  If you have a *manuscriptstyle.docx* that is built for a specific journal then you can easily change the filename for ease of use: *natureclimatechangestyle.docx*. Just remember to make the change in the YAML too.

## Citing

Citing in the text is actually very straightforward and is compataible with all your major bibliography generating software (Zotero, Mendeley, Endnote, etc). The reason is that all of these software can easily export a bibtex library file.  So nothing in the way you organize your citations needs to change. For example, here are the basic instructions for outputting the library from Zotero:

\

- Select the library you wish to export to BibTex in Zotero
- From Zotero toolbar dropdown menu, select Export Library
- On the next screen, choose format BibTex, and click OK
- Navigate to the directory where you want to save your file, save it as     filename.bib

\

For our use, save the BibTex libary in the folder with the markdown file. Here it is named **references.bib**. Go ahead and click on it.  It is just a list of all the BibTex entries from your citing library.  If you clean up any errors in Zotero (for example) the BibTex will be updated.  You can also easily fix them in Rstudio, if needed. For example, I sometimes need to change CO2 to [CO\textsubscript{2}] (using Latex) in an entry.  Ok, look up at your YAML and you will see **bibliography: references.bib**.  This supplies markdown with all of our possible citations and will automatically generate a bibliography at the bottom of the document.  The bibliography will only be created with the citations that we actually use.  

\ 

Ok, time to cite.  The format for citing in the text is very easy and uses the **'ID'** of each Bibtex entry. Navigate back to **references.bib** and simply find the **'ID'** after the start of the entry Article{yourIDishere,. To cite, just place the ID with the @ symbol inside square brackets [@barton2010whole].  You can combine as many as you need [@brooks1996effects, @bowling2003tunable, @bickford2009high]. You separate the citations with whatever the journal requires (, or ; ). Often you may have some qualifiers with your citation. These can be inserted inside the brackets [see @barton2010whole Figure 1] Last, you may want to cite in-line. There are a couple of ways to do this.  First, @barton2010whole mentions that the best way is just remove the brackets. Alternately, Bowling et al. [-@bowling2003tunable] states to type the name but insert a minus sign inside the []. I would stick to removing the [] for inline because typing the name does not have the formatting for the journal (look at the differences in 'et al.'). Last, look down at the end of this document.  I have created a section called **Bibliogrpahy**.  Markdown will generated a citation list in the rendered document based on what you cite.

## CSL: citation formatting

The last bit of information in are YAML involves the formatting for our citations, both in the text and in our **Bibliogrpahy**.  


Notice that when you render the document, the 'et al.' of these two inline citations look different.  **csl: plant-cell-environment.csl** in our YAML sets the style and the actual file is in our markdown folder, with everything else. CSL stands for Citation Style Language and every single citing software uses them.  Often when you Zotero (or whatever) you search for a journal style and add it to you software's collection.  All you are doing is downloading a CSL. There are plenty of places to download them (https://www.zotero.org/styles). So find the one you need and stick it in the folder and change the YAML. In the off chance your paper gets rejected, download the next one and update your YAML.  When you render the document, it will make the changes for you. Voila!!

# Results

## Study site

Place your awesome results here

# Discussion

Change the world with your awesome insight here

# Acknowledgements

We do not thank Darth Vader.  He is a pain in the ass

# Author Contributions

Rey did just about everything.  Everyone else on the author list has moved to the afterlife

# Tables

# Figures

# Bibliography