---
title: "Mystery Future FACE experiment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment

This assignment investigates the response of a forest to predicted future climate change. You are tasked with evaluating the sink capacity/potential of this forest under current and future atmospheric CO~2~ conditions.

\

There are data sets to compute the CO~2~ fertilization effect on photosynthesis and aboveground NPP. I have changed the dates of the experiment, but they cover 3 years of growth under eCO~2~ and aCO~2~. Rings are 25m diameter circular plots. For this future FACE site the CO~2~ fumigation was fully operational in 2021. We will consider early years as pre-treatment or partial fumigation. 

\

*You will have to be diligent with unit conversions, converting dates, variable names, etc.*

\

1) **Photosynthesis**. Visualize and evaluate the response of foliage photosynthesis to eCO~2~ compared to aCO~2~.  In lecture, we learned that 'time' was a critical component with evaluating FACE experiments. Is photosynthesis stimulated by eCO^2 in this experiment. If so, is the response sustained over the 3 year interval? Visualize mean photosynthesis data (with standard errors) and the eCO~2~ response ratio of photosynthesis through time.

\

The response ratio is easy to calculate (eCO~2~/aCO~2~) but you will have to make separate subsets and merge them together so photosynthesis is side to side (also change variable name). Then you can make the calculation.  **+0.5 bonus point if you can make this a clean 2 panel figure with a shared x axis.**. You will have to add labels to each panel (text(x=, y= ,"a")) so you can distinguish each panel in the caption and in the text.

\

2) **Litterfall**. Compute annual productivity as the sum of all litterfall components for for 2021, 2022 & 2023.  Assume all biomass components are comprised of 47% C. Visualize annual productivity with all of the components. Are any patterns noticeable between years or with CO~2~ treatments? *I will give an example of a stacked bar plot in class*

\

3) **ANPP**. Here, we will define aboveground net primary productivity (ANPP) as the productivity of stemwood biomass production + fine twig production + seed production + leaf production. Visualize and evaluate mean ANPP for aCO~2~ and eCO~2~ treatments for 2021, 2022 & 2023. **ANPP must be reported in g C m^-2^ yr ^-1^**. Is there a CO~2~ effect? Why does this match/not match what you find in photosynthesis?

\

4) **Bug**. This experimental site is also subject large insect outbreaks. Insects have caused several defoliation events during this time period. Visualize these defoliation events and speculate if there was a CO~2~ effect? Would a CO~2~ effect be expected? **+0.5 bonus point if you can add transparent colored polygons over the suspected defoliation events**

## Metadata

For this experiment, rings 2,3,4 are aCO~2~ and 1,5,6 are eCO~2~

**Leaf photosynthesis**

Photosynthesis was measured in discrete campaigns and the principal age class of leaves  were present at each time point. Measurements were made using a set of Li-Cor model 6400 portable photosynthesis systems using  infra-red gas analysis. Only the first photosynthesis measurement, made at the CO~2~ concentration the trees were growing in, is included here. These CO~2~ concentrations are nominally 396 ppm for aCO~2~ and 546 ppm for eCO~2~. Units for leaf net photosynthesis are umols m^-2^ s^-1^.

**Litterfall**

Dry mass of litterfall was collected on a monthly basis in .02m^2^ collection baskets. This includes both foliage, twig, bark and seed litterfall. Samples were collected and sorted into components and weighed. All litter collections are reported in dry biomass (g). They collection dates were not perfect monthly increments, but assume they are for this exercise. There are 2 cases where really big branches landed on the litter traps and were counted.  Make sure and remove these data (we will do this in class)

**Tree biomass**

The diameter of each tree was measured at 1.3m height at approximately monthly intervals starting February 2011, two years prior to commencement of the full CO~2~ treatment. Manual band dendrometers were used to monitor stem diameter changes. The permanently placed bands consisted of plastic straps graduated with a vernier scale placed around a tree. These trees were surveyed annually (or more frequently) and annual values were used to compute tree biomass according to published allometric regressions. This data set includes the total wood biomass calculated from allometry, *not the annual wood production*.
